### 基础环境
user: work
mysql_port: 3306
pack_home: "/home/{{ user }}"
basedir: "{{ pack_home }}/mysql"
datadir: "{{ pack_home }}/data/mysql"
logdir: "{{ basedir }}/logs"

mysql_package_name: mysql-5.7.31-linux-glibc2.12-x86_64
mysql_package: "{{ mysql_package_name }}.tar.gz"
download_url: "https://nginx-qa.fit2cloud.com/tools/{{ mysql_package }}"


### MySQL root user password
root_password: Password123@mysql

### MySQL Socket
mysql_socket: "{{ basedir }}/run/mysql.sock"


### MySQL rep user password
rep_user: rep
rep_password: Password123@rep

### MySQL remote user password
remote_user: remote
remote_user_password: Password123@remote

---
# Variables here are applicable to all host groups



script_folder: "/etc/keepalived/script/"
vrrp: "192.168.34.99"
virtual_router_id: "19"
eth: "eth0"


